import { useState, type FormEvent } from 'react';
import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { ArrowLink, PageIntro, SectionHeading } from './site-shell';
import { demoLabel, images, useSite, type Enquiry, type GalleryItem, type Project } from '@/lib/site-data';

export function ContactBand() { return <section className="contact-band"><div className="wrap"><div><span className="eyebrow">A CONVERSATION BEGINS HERE</span><h2 className="section-title">Let's Discuss Your<br />Next Space.</h2></div><Button asChild variant="gold"><Link to="/contact">Make an Enquiry <span>↗</span></Link></Button></div></section>; }
export function ProjectCard({ project }: { project: Project }) { return <article className="project-card"><Link className="project-card-image" to="/projects/$id" params={{ id: project.id }}><img src={project.image} alt={`${project.name} architectural concept`} loading="lazy" /></Link><div className="project-card-info"><div><span className="meta">{project.category} / {project.status} / Demo concept</span><h3>{project.name}</h3><p>{project.location}</p></div><Link to="/projects/$id" params={{ id: project.id }} aria-label={`Explore ${project.name}`}>↗</Link></div></article>; }
export function HomePage() { const { data } = useSite(); const h = data.heroSettings; return <>
  <section className="hero"><img className="hero-image" src={h.image} alt="Contemporary residential architecture at dusk" /><div className="hero-overlay" style={{ '--overlay': `${h.overlay}%` } as React.CSSProperties} /><div className="wrap hero-content"><span className="eyebrow">{h.eyebrow}</span><h1 className="display-title preserve-lines">{h.title}</h1><p>{h.subtitle}</p><div className="hero-actions"><Button asChild variant="gold"><Link to="/projects">{h.cta} <span>↗</span></Link></Button><Button asChild variant="outlineLight"><Link to="/contact">{h.secondCta} <span>↗</span></Link></Button></div><div className="hero-bottom wrap"><span>{h.location}</span><span className="scroll-indicator">Scroll to explore</span></div></div></section>
  <section className="section"><div className="wrap"><div className="editorial-grid"><div><span className="eyebrow">THE NEETYA APPROACH</span><h2 className="editorial-title preserve-lines">{data.aboutSettings.approachHeading}</h2></div><p className="body-copy">{data.aboutSettings.approachText}</p></div><img className="wide-image" src={data.aboutSettings.image} alt="Contemporary residential setting surrounded by nature" loading="lazy" /><div className="image-caption"><span>Spaces shaped by intention</span><span>Pune, Maharashtra</span></div></div></section>
  <section className="section section-dark"><div className="wrap"><div className="projects-heading"><SectionHeading eyebrow="THE PORTFOLIO" title="Selected Developments" description="Spaces designed around the way people live, work and grow." /><ArrowLink to="/projects">View all projects</ArrowLink></div><div className="project-grid">{data.projects.filter(p => p.featured).slice(0,2).map(p => <ProjectCard key={p.id} project={p} />)}</div><p className="demo-note">{demoLabel}. Project names, statuses and images are illustrative, not verified developments.</p></div></section>
  <PhilosophySection />
  <section className="section"><div className="wrap"><div className="about-split"><img src={data.aboutSettings.image} alt="Landscaped contemporary residences" loading="lazy" /><div className="about-copy"><span className="eyebrow">ABOUT NEETYA DEVELOPERS</span><h2 className="section-title preserve-lines">{data.aboutSettings.heading}</h2><p className="body-copy">{data.aboutSettings.story}</p><div className="principles">{data.aboutSettings.principles.map((p,i)=><div className="principle" key={i}><span>{String(i+1).padStart(2,'0')}</span>{p}</div>)}</div><div style={{marginTop:35}}><ArrowLink to="/about">Discover our story</ArrowLink></div></div></div></div></section>
  <section className="section" style={{paddingTop:0}}><div className="wrap"><div className="stats">{data.aboutSettings.stats.map((s,i)=><div className="stat" key={i}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><p className="demo-note">Snapshot figures are editable demo placeholders, not verified company statistics.</p></div></section>
  <section className="section"><div className="wrap"><div className="projects-heading"><SectionHeading eyebrow="WHAT WE DO" title="A Considered Approach\nto Development" /><ArrowLink to="/services">Explore services</ArrowLink></div><div className="services-grid">{data.services.map((s,i)=><article className="service-item" key={s.id}><span>{String(i+1).padStart(2,'0')} / 06</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></div></section>
  <WhySection />
  <section className="section"><div className="wrap"><SectionHeading eyebrow="THE JOURNEY" title="From Vision to Place" /><Journey /></div></section>
  <section className="section section-dark"><div className="wrap"><div className="projects-heading"><SectionHeading eyebrow="VISUAL JOURNAL" title="Spaces in Focus" /><ArrowLink to="/gallery">View gallery</ArrowLink></div><GalleryGrid items={data.gallery.slice(0,4)} /></div></section>
  <TestimonialsSection />
  <LocationSection />
  <ContactBand />
</>; }
export function PhilosophySection() { const {data}=useSite(); return <section className="philosophy-band"><img src={data.philosophy.image} alt="Contemporary architectural form" loading="lazy" /><div className="wrap philosophy-inner"><span className="eyebrow">OUR PHILOSOPHY</span><h2 className="section-title preserve-lines">{data.philosophy.heading}</h2><div className="philosophy-list">{['LOCATION','DESIGN','QUALITY'].map((title,i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{data.philosophy.descriptions[i]}</p></article>)}</div></div></section>; }
export function WhySection() { const {data}=useSite(); return <section className="section"><div className="wrap why-split"><div><span className="eyebrow">WHY NEETYA</span><h2 className="section-title preserve-lines">{data.whyUs.heading}</h2><p className="body-copy">A good development begins with the right questions. We consider how a place looks, how it works, and how it feels to live with over time.</p><div className="why-list">{data.whyUs.items.map((item,i)=><div key={i}><span>0{i+1}</span>{item}</div>)}</div></div><img src={data.whyUs.image} alt="Contemporary living room interior" loading="lazy" /></div></section>; }
export function Journey() { return <div className="timeline">{['VISION','PLANNING','DESIGN','DEVELOPMENT','DELIVERY'].map((s,i)=><div className="timeline-item" key={s}><span>0{i+1}</span><h3>{s}</h3></div>)}</div>; }
export function TestimonialsSection() { const {data}=useSite(); const published=data.testimonials.filter(t=>t.published); if (!published.length) return null; return <section className="section"><div className="wrap quote"><span className="eyebrow">WORDS & PERSPECTIVES</span><blockquote>“{published[0].feedback}”</blockquote><p>{published[0].name} · {published[0].location} · {published[0].project}</p><p className="demo-note">Illustrative testimonial — not a verified customer review.</p></div></section>; }
export function LocationSection() { const {data}=useSite(); return <section className="section"><div className="wrap location-split"><img src={images.residencesImage} alt="Natural landscape around contemporary architecture" loading="lazy" /><div><span className="eyebrow">OUR LOCATION</span><h2 className="section-title">Rooted in Pune</h2><p className="body-copy">Bhukum. Mulshi. Pune. Maharashtra. A setting where the energy of a growing city meets the openness of the surrounding landscape.</p><p className="address">{data.websiteSettings.address}</p></div></div></section>; }
export function AboutPage() { const {data}=useSite(); return <><PageIntro eyebrow="01 / ABOUT US" title={data.aboutSettings.heading} description="A thoughtful perspective on the places we make and the people who live in them." /><section className="section"><div className="wrap editorial-grid"><div><span className="eyebrow">OUR STORY</span><h2 className="editorial-title preserve-lines">{data.aboutSettings.approachHeading}</h2></div><p className="body-copy">{data.aboutSettings.story}</p></div><div className="wrap"><img className="wide-image" src={data.aboutSettings.image} alt="Residential architecture in a landscaped setting" loading="lazy" /></div></section><section className="section"><div className="wrap"><SectionHeading eyebrow="OUR PRINCIPLES" title="What Guides Us" /><div className="principles">{data.aboutSettings.principles.map((p,i)=><div className="principle" key={i}><span>0{i+1}</span>{p}</div>)}</div></div></section><section className="section"><div className="wrap"><div className="stats">{data.aboutSettings.stats.map((s,i)=><div className="stat" key={i}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><p className="demo-note">Snapshot figures are editable demo placeholders, not verified company statistics.</p></div></section><WhySection /><ContactBand /></>; }
export function ProjectsPage() { const {data}=useSite(); const [filter,setFilter]=useState('All'); const projects=data.projects.filter(p=>filter==='All'||p.category===filter||p.status===filter); return <><PageIntro eyebrow="02 / OUR PORTFOLIO" title="Selected\nDevelopments" description="Spaces designed around the way people live, work and grow." /><section className="section"><div className="wrap"><div className="filters">{['All','Residential','Commercial','Upcoming','Completed'].map(f=><Button key={f} variant="plain" className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="project-grid">{projects.map(p=><ProjectCard project={p} key={p.id} />)}</div>{!projects.length && <p className="body-copy">No demo projects in this category yet.</p>}<p className="demo-note">{demoLabel}. Names, statuses and imagery do not represent verified developments.</p></div></section><ContactBand /></>; }
export function ProjectDetailPage({ id }: { id: string }) { const {data}=useSite(); const p=data.projects.find(p=>p.id===id); if(!p) return <><PageIntro eyebrow="PROJECTS" title="Project not found" /><section className="section wrap"><ArrowLink to="/projects">Back to projects</ArrowLink></section></>; return <><section className="detail-hero"><img src={p.image} alt={`${p.name} architectural concept`} /><div className="wrap"><span className="eyebrow">{p.category} / {p.status} / ILLUSTRATIVE CONCEPT</span><h1 className="display-title">{p.name}</h1><p>{p.location}</p></div></section><div className="wrap detail-facts"><div><small>Location</small><strong>{p.location}</strong></div><div><small>Property type</small><strong>{p.category}</strong></div><div><small>Demo status</small><strong>{p.status}</strong></div></div><section className="section"><div className="wrap editorial-grid"><div><span className="eyebrow">PROJECT OVERVIEW</span><h2 className="section-title">A place with<br />perspective.</h2></div><div><p className="body-copy">{p.overview}</p><p className="demo-note">Illustrative portfolio concept only. Please contact the company for verified project information.</p></div></div></section><section className="section" style={{paddingTop:0}}><div className="wrap detail-list"><div><h3>Key highlights</h3><p>{p.highlights}</p></div><div><h3>Amenities</h3><p>{p.amenities}</p></div><div><h3>Configurations</h3><p>{p.configurations}</p></div></div></section><section className="section section-dark"><div className="wrap"><SectionHeading eyebrow="THE VISUAL STORY" title="Project Gallery" /><div className="detail-gallery">{p.images.slice(0,2).map((img,i)=><img key={i} src={img} alt={`${p.name} concept visual ${i+1}`} loading="lazy" />)}</div></div></section><section className="section"><div className="wrap editorial-grid"><div><span className="eyebrow">THE SETTING</span><h2 className="section-title">Location &<br />Connections</h2></div><p className="body-copy">{p.advantages}</p></div></section><ContactBand /></>; }
export function ServicesPage() { const {data}=useSite(); return <><PageIntro eyebrow="03 / EXPERTISE" title="The Work Behind\nEvery Space" description="Development, planning and perspective brought together with intention." /><section className="section"><div className="wrap services-grid">{data.services.map((s,i)=><article className="service-item" key={s.id}><span>{String(i+1).padStart(2,'0')} / {String(data.services.length).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section><PhilosophySection /><section className="section"><div className="wrap"><SectionHeading eyebrow="HOW WE WORK" title="The Development Journey" /><Journey /></div></section><ContactBand /></>; }
export function PhilosophyPage() { return <><PageIntro eyebrow="04 / PHILOSOPHY" title="A Thoughtful Way\nto Build" description="We believe the spaces we create should feel as considered as the lives lived within them." /><PhilosophySection /><WhySection /><ContactBand /></>; }
export function WhyPage() { return <><PageIntro eyebrow="05 / WHY NEETYA" title="The Value of\nThinking Further" /><WhySection /><section className="section"><div className="wrap"><SectionHeading eyebrow="OUR PROCESS" title="Every Detail Has a Purpose" /><Journey /></div></section><ContactBand /></>; }
export function GalleryGrid({items}: {items:GalleryItem[]}) { const [active,setActive]=useState<number|null>(null); return <><div className="gallery-grid">{items.map((item,i)=><Button variant="plain" className="gallery-tile" key={item.id} onClick={()=>setActive(i)} aria-label={`Preview ${item.title}`}><img src={item.image} alt={item.title} loading="lazy" /><span className="gallery-tile-label"><strong>{item.title}</strong><small>{item.category}</small></span></Button>)}</div>{active!==null && items[active] && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Image preview" onKeyDown={e=>{if(e.key==='Escape')setActive(null); if(e.key==='ArrowLeft')setActive((active-1+items.length)%items.length); if(e.key==='ArrowRight')setActive((active+1)%items.length);}} tabIndex={-1}><Button variant="icon" className="lightbox-close" aria-label="Close preview" onClick={()=>setActive(null)}>×</Button><Button variant="icon" className="lightbox-prev" aria-label="Previous image" onClick={()=>setActive((active-1+items.length)%items.length)}>‹</Button><img src={items[active].image} alt={items[active].title} /><Button variant="icon" className="lightbox-next" aria-label="Next image" onClick={()=>setActive((active+1)%items.length)}>›</Button><div className="lightbox-caption">{items[active].title} <small> / {items[active].category}</small></div></div>}</>; }
export function GalleryPage() { const {data}=useSite(); const [filter,setFilter]=useState('All'); const items=data.gallery.filter(g=>filter==='All'||g.category===filter); return <><PageIntro eyebrow="06 / VISUAL JOURNAL" title="Architecture in\nPerspective" description="A visual exploration of places, materials and the moments between." /><section className="section"><div className="wrap"><div className="filters">{['All','Architecture','Projects','Interiors','Construction','Lifestyle'].map(f=><Button key={f} variant="plain" className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</Button>)}</div><GalleryGrid items={items} />{!items.length && <p className="body-copy">No images in this category yet.</p>}<p className="demo-note">Imagery is illustrative demo content.</p></div></section><ContactBand /></>; }
export function ContactPage() { const {data,update}=useSite(); const [success,setSuccess]=useState(false); const [form,setForm]=useState({name:'',phone:'',email:'',interest:'Residential Project',message:''}); const submit=(e:FormEvent)=>{e.preventDefault(); const entry:Enquiry={...form,id:crypto.randomUUID(),date:new Date().toISOString(),status:'New'};update('enquiries',[entry,...data.enquiries]);setSuccess(true);setForm({name:'',phone:'',email:'',interest:'Residential Project',message:''});}; const s=data.websiteSettings; return <><PageIntro eyebrow="07 / CONTACT" title="Let's Begin a\nConversation" description="Whether you have a question or an idea, we would be glad to hear from you." /><section className="section"><div className="wrap contact-layout"><div><span className="eyebrow">GET IN TOUCH</span><h2 className="editorial-title">A place to<br />start.</h2><p className="body-copy">Share a little about what you have in mind. We will be in touch when contact details are configured for this demonstration.</p><p className="address">{s.address}</p><p className="body-copy">{s.phone || 'Phone available on request'}<br />{s.email || 'Email available on request'}{s.hours && <><br />{s.hours}</>}</p></div><div>{success ? <div className="form-success" role="status">Thank you. Your enquiry has been received.</div> : <form onSubmit={submit} className="form-grid"><label className="field">Full Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} /></label><label className="field">Phone Number<input required type="tel" minLength={7} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} /></label><label className="field">Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} /></label><label className="field">Interested In<select value={form.interest} onChange={e=>setForm({...form,interest:e.target.value})}>{['Residential Project','Commercial Project','Upcoming Project','General Enquiry'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field field-full">Message<textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} /></label><div className="field-full"><Button type="submit" variant="gold">Send Enquiry ↗</Button><p className="demo-note">Demo only — your enquiry is saved in this browser, not sent to the company.</p></div></form>}</div></div></section><LocationSection /></>; }
